### ISSUE TITLE
RPC calls are not being logs after removing PPL

### ISSUE THREAD

**Issue by g3rzi** [zeronetworks/rpcfirewall#10]
I saw you answer: 
https://github.com/zeronetworks/rpcfirewall/issues/4#issuecomment-970429333  

But when I am trying to trace the RPC requests from `dockerd.exe` after removing the PPL using Mimikatz, it still doesn't work.  
Although I doesn't a PPL process as far as I know.
Any idea?  

![image](https://user-images.githubusercontent.com/11998736/145820501-19882c7e-7fd9-44c6-8f8d-b8a73350348e.png)

**Comment by sagiesec** [comment]
Interesting use case :)

According to the debug message, I looks like the there are no RPC interfaces registered in the runtime (RPCRT4.DLL). 
The the docker daemon exposing any RPC interfaces? (you can try and validate with RPCView for example).

The UUID registration checks makes sure we are registering on "valid" RPC Servers, and not merely RPC clients etc. 
If you wish, you can compile it without these  checks. Simply remove the "checkIfRegisteredUUIDsForProcess" and "checkIfReleventRegisteredEndpointsForProcess" conditions in https://github.com/zeronetworks/rpcfirewall/blob/master/rpcFirewall/dllmain.cpp#L751

**Comment by g3rzi** [comment]
Thank you,
You are right, it seems that `dockerd.exe` doesn't have RPC server:  
```powershell
PS C:\Users\Administrator> Get-RpcServer 'C:\Program Files\Docker\dockerd.exe' -DbgHelpPath "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll"
PS C:\Users\Administrator>
```  

For some reason I thought it had because of the message:  

> "`Process 2344 contains RPC module!"
