### ISSUE TITLE
Does NdrClientCall3 is being hook?

### ISSUE THREAD

**Issue by g3rzi** [zeronetworks/rpcfirewall#11]
Hi,

I have an RPC server that uses `NdrClientCall3`.  
Does `NdrClientCall3` is being hooked?   
I saw that you implemented it here:  
https://github.com/zeronetworks/rpcfirewall/blob/556b191adf853a6489a2f14dc607f3fb9bb4d935/rpcFwManager/rpcHooks.cpp#L159   

But I don't see it in the DLL:  
https://github.com/zeronetworks/rpcfirewall/blob/556b191adf853a6489a2f14dc607f3fb9bb4d935/rpcFirewall/dllmain.cpp#L125-L141

**Comment by sagiesec** [comment]
From my experiments I've noticed that this mainly causes duplicated messages, as NdrStubCall3 Normally calls NdrStubCall2 if the transfer syntax is NDR, which theoretically should always be the case.  

May be a good idea to add this anyway, to cover for abnormal instances where this is not the case. 
Do you have any examples of services where NdrStubCall3 is not calling NdrStubCall2? 

![image](https://user-images.githubusercontent.com/61778471/146166976-b4041a3c-fecd-49fb-b659-56a995fda72a.png)
