### ISSUE TITLE
Server 2008 R2 Zero Logon

### ISSUE THREAD

**Issue by MichalisDBA** [zeronetworks/rpcfirewall#18]
Hello.

I have setup a lab environment with a Windows 2008 R2 server vulnerable to zero logon attack. I have another PC that runs Ping Castle to check for zero logon vulnerability. It finds the venerability successfully.

I installed to Windows 2008 the rpcfirewall and protect all the processes with action block.

I run again from the PC the ping castle software and still finds the DC vulnerable to this attack.

In Windows server 2008 the rpcfw events are not storing anything nor your software protects from this attack.

Can you verify please?

**Comment by sagiesec** [comment]
Currently RPCFW does not support Server 2008. It is in the backlog, hopefully in the near future it will support 2008 also.
