### ISSUE TITLE
windows 7 enterprise

### ISSUE THREAD

**Issue by strongBurger** [zeronetworks/rpcfirewall#25]
Hello,

I tried installing rpcfirewall on my machine, just to see.
But does not seem to be working.

Is rpcfirewall supposed to be working on win7 x64 sp1 Enterprise French ?

Best regards

![Screenshot_3](https://user-images.githubusercontent.com/99596624/172727503-8af15339-ed31-4c99-8169-b4b2e0e30ac4.png)
![Screenshot_4](https://user-images.githubusercontent.com/99596624/172727510-28bc5217-100f-4387-aa55-17599b795dcd.png)

**Comment by sagiesec** [comment]
RPCFW doesn't work on Win7. 
I suggest trying it on server machines 2012 and up :)
