### ISSUE TITLE
[Feature Request] sAMAccountName filtering

### ISSUE THREAD

**Issue by 1mm0rt41PC** [zeronetworks/rpcfirewall#27]
Is it possible to add a filtering based on the IP and on the username ?
For example block all RPC call made by domain admin (prefix `da_`) if sourceip is not `10.10.10.1` (admin castle)
```
fw:uuid:* action:block audit:true not_saddr:10.10.10.1 username:da_john.doe
fw:uuid:* action:block audit:true not_saddr:10.10.10.1 username_pattern:da_*
```

**Comment by sagiesec** [comment]
Working on it for the upcoming version :)

**Comment by sagiesec** [comment]
Added SID parameter also for the RPC Firewall module from version 2.1.0
