### ISSUE TITLE
RpcFw.conf.AuditAll template file missing

### ISSUE THREAD

**Issue by k4nfr3** [zeronetworks/rpcfirewall#28]
Hi,

your documentation was mentioning this template for AuditAll.

But it doesn't seem to exist any more

Kind regards

**Comment by sagiesec** [comment]
Hi. 
This is the default configuration downloaded with the latest release. 
It audits all RPC Firewall activities 
(
  so you will need to deploy the "fw" module: 
  /install fw
  /start fw
)
