### ISSUE TITLE
How do I simulate attacks on AD to find out if RPC firewall is functioning properly?

### ISSUE THREAD

**Issue by Blason** [zeronetworks/rpcfirewall#34]
Hi team,

I am testing out RPC Firewall wondering How do I test out the attacks and prevention capabilities on Active Directory?

TIA
Blason R

**Comment by sagiesec** [comment]
I believe I've already answered in our slack, but just so there's documentation here as well: 

Here are some ideas:
[SharpHound](https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors)
[CornerShot](https://github.com/zeronetworks/cornershot)
[Impacket](https://github.com/fortra/impacket/tree/master) attacks ( [addComputer](https://github.com/fortra/impacket/blob/master/examples/addcomputer.py), [Atexe](https://github.com/fortra/impacket/blob/master/examples/atexec.py), [dcomexe](https://github.com/fortra/impacket/blob/master/examples/dcomexec.py), [PsExec](https://github.com/fortra/impacket/blob/master/examples/psexec.py), [reg](https://github.com/fortra/impacket/blob/master/examples/reg.py), and much more...)
[PetitPotam](https://github.com/topotam/PetitPotam)
[Coercer](https://github.com/p0dalirius/Coercer)
Built in windows commands on remote computer ([wmic](https://huntsman-dfir.medium.com/lateral-movement-with-wmi-windows-management-instrumentation-67639e9456cb), [net](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/net-commands-on-operating-systems), ...)
