### ISSUE TITLE
RPC calls not being logged

### ISSUE THREAD

**Issue by oshaked1** [zeronetworks/rpcfirewall#4]
While experimenting, I came across an issue where several RPC calls that are triggered by remote usage of psexec are not logged.
I am using the following bare minimum configuration (the .txt at the end was added in order to upload this):
[RpcFw.conf.txt](https://github.com/zeronetworks/rpcfirewall/files/7541333/RpcFw.conf.txt)

When running psexec, the only event that is logged is the map request on the endpoint mapper interface:
[RPCFWP.evtx.txt](https://github.com/zeronetworks/rpcfirewall/files/7541354/RPCFWP.evtx.txt)

A packet capture clearly shows that more RPC calls were performed:
[remote_psexec.pcap.txt](https://github.com/zeronetworks/rpcfirewall/files/7541359/remote_psexec.pcap.txt)

I have also tried using no configuration file, but the calls in question are still not logged.

**Comment by sagiesec** [comment]
This is a known issue. 
The reason being that some Windows versions have the services.exe process running as protected. 
Therefore you can't inject the rpcFirewall.dll into this process. 

If you wish to protect a server, I suggest using the rpc filters for remote services [MS-SRVS], and the RPC-Firewall for the rest.

**Comment by oshaked1** [comment]
Thanks for the suggestion!

**Comment by g3rzi** [comment]
Removing PPL using Mimikatz (i.e. remove it from Lsass):
```
mimikatz # !+
mimikatz # !processprotect /process:lsass.exe /remove
```  

Reference:
https://itm4n.github.io/lsass-runasppl/
https://twitter.com/MME_IT/status/419208174046949376/photo/1
