### ISSUE TITLE
Error when loading rpcFireWall.dll: "binary is not signed correctly"

### ISSUE THREAD

**Issue by g3rzi** [zeronetworks/rpcfirewall#9]
When I am trying to audit a process called `vmcompute.exe`:  
```
rpcFwManager.exe /process vmcompute.exe
```

It fails with the following message:  
```
* This break indicates this binary is not signed correctly: \Device\HarddiskVolume4\Windows\System32\rpcFireWall.dll
* and does not meet the system policy.
* The binary was attempted to be loaded in the process: \Device\HarddiskVolume4\Windows\System32\vmcompute.exe
* This is not a failure in CI, but a problem with the failing binary.
* Please contact the binary owner for getting the binary correctly signed.
```

Here is a print screen of what I tried to do:  
![image](https://user-images.githubusercontent.com/11998736/145805311-e053aafe-74ed-4258-9d7d-cc43ae170221.png)

**Operation system:** Windows Server 2019 1809 (OS Build 17763.2114).

**Comment by sagiesec** [comment]
We may add a signed binary in an upcoming version. 
Thanks you for the suggestion

**Comment by g3rzi** [comment]
Thanks.
I will appreciate if you can reference this issue number to the version that will add this fix.  
I will close it for now.

**Comment by sagiesec** [comment]
Release v1.0.3 now has signed code.

**Comment by g3rzi** [comment]
Great, thank you for the update :)
